FIXME FTBFS; disabling mesa_p260c
See commit 354d30d

    Compiling realtime hal/drivers/mesa_p260c.c
    hal/drivers/mesa_p260c.c:82:5: error: unknown type name ‘bool’
	 bool input_valid;
	 ^~~~
    hal/drivers/mesa_p260c.c: In function ‘read_all_data’:
    hal/drivers/mesa_p260c.c:663:45: error: ‘true’ undeclared (first use in this function)
			 boards[j].input_valid = true;
						 ^~~~
    hal/drivers/mesa_p260c.c:663:45: note: each undeclared identifier is reported only once for each function it appears in
    hal/drivers/mesa_p260c.c: In function ‘serial_port_task’:
    hal/drivers/mesa_p260c.c:832:33: error: ‘false’ undeclared (first use in this function)
	     boards[i].input_valid = false;
				     ^~~~~
    Makefile:1749: recipe for target 'objects/posix/hal/drivers/mesa_p260c.o' failed