Linkage of tcl/hal.so against libtclstub.a is necessary for several tcl functions
This commit removed the linkage against libtclstub.a because it produced warnings
of possible unused symbols.
machinekit/machinekit@d1fed9c#diff-b95f3ce6cb4f8632848c66ea2be6b1f5

Reverting machinekit, so that it has the same linkage in tcl/hal.so
that machinekit-hal does, removes the 'undefined reference to tclStubPtr' error.

Signed-off-by: Mick <arceye@mgware.co.uk>